### ISSUE TITLE
How to sponsor ?

### ISSUE THREAD

**Issue by roonie007** [jd-solanki/anu#117]
Thanks for this project, I have been following it since October and waiting for TailwindCSS support :).

Maybe you should activate the sponsoring on github or setup a patreon, so people can support you and the project.

Keep up the good work

**Comment by jd-solanki** [comment]
Thank you so much for your kind words and support of the project! 😇  I'm glad to hear that you have been following it since October and are excited about the addition of TailwindCSS support.

Your suggestion to set up a way for people to support the project, such as through GitHub Sponsors or Patreon, is greatly appreciated. I will definitely consider it and will setup soon. 💯 

In the meantime, there are other ways you can support the project, such as by contributing code, testing, or spreading the word about it to others who might be interested. Thank you again for your support, and I appreciate all of your help in making this project a success.

Regards 🙏🏻

**Comment by jd-solanki** [comment]
If anyone wants to support the project please follow me on twitter at [@me_jd_solanki](https://twitter.com/me_jd_solanki), I will announce when sponsorship will be available.

Thanks for your support 😊

**Comment by jd-solanki** [comment]
@roonie007 Sponsorship is available now 😇 

Twitter announcement: https://twitter.com/me_jd_solanki/status/1611343092178898945

Will add the sponsors' images tonight.

Thanks for your interest 🙏🏻
