### ISSUE TITLE
ESlint errors

### ISSUE THREAD

**Issue by zguolee** [jd-solanki/anu#12]
I noticed that the project has a `@antfu/eslint-config-vue` package and and there are some eslint errors(e.g. `'vue' import should occur before import of '@/composables/useLayer'` in `AAvatar.tsx`). But I don't know if I should fix it, because it will affect the code style. In addition I tried to switch it to [@antfu/eslint-config](https://github.com/antfu/eslint-config) and delete the unused config. But there were some other eslint errors, such as `'xxx' was used before it was defined`. Would you consider using [@antfu/eslint-config](https://github.com/antfu/eslint-config), which can bring better code specification to the project.

**Comment by jd-solanki** [comment]
Hi,

Thanks for raising this issue. When I started building anu, linting wasn't configured properly. At the moment, it looks like eveything about linting is working fine.

_Definitely, we can improve it a bit._

Regarding import order error, I think that file was saved before I configured eslint so it is fine to change the import order as you mentioned. I am getting the same in my setup 😉 

For `'xxx' was used before it was defined` this correct according to linting but you will only see this error in `ATable` I guess because only there I had to use the const before it was defined. However, Due to [JS hoisting](https://developer.mozilla.org/en-US/docs/Glossary/Hoisting) even if you write the variable declaration after its usage it will not result in error.
Moreover, You might encounter `'xxx' was used before it was defined` in your code if you have similar logic as we have in ATable. While I started using composition API I did encounter this "used before defined error" because at some point your two composables might depend on each other.

Hence, Just try your best to resolve the `'xxx' was used before it was defined` however if there is the circular dependency you have to suppress the error.

Please let me know if you have any further queries. I am happy to improve anu.

> _P.S. If you have anything regarding improvements to the engineering of this project, I am happy to discuss it._

**Comment by zguolee** [comment]
Thank you, I have no other problems anymore.😁
