### ISSUE TITLE
v0.11.0: "sass" not found

### ISSUE THREAD

**Issue by ManUtopiK** [jd-solanki/anu#90]
I just updated to v0.11.0, but its missing dependencies for `preset-theme-default` :
```
[vite:css] Preprocessor dependency "sass" not found. Did you install it?
file: .../node_modules/.pnpm/@anu-vue+preset-theme-default@0.11.0/node_modules/@anu-vue/preset-theme-default/dist/styles.scss
```

Resolved with `pnpm add -D sass`.

**Comment by benatkin** [comment]
I don't think this goes as a dependency in `package.json` because Sass needs to be installed differently according to the platform - different for vite and nuxt https://vitejs.dev/guide/features.html#css-pre-processors https://nuxtjs.org/docs/features/configuration/#pre-processors

Removing the Sass dependency all together is an idea. I don't feel strongly either way. It used to require installing a C library but doesn't anymore.

**Comment by jd-solanki** [comment]
Hey,

if you have followed the [new](https://anu-vue.netlify.app/guide/getting-started/installation.html) installation steps of v0.11.0, you might have noticed that you are importing scss file in `main.ts` file. For scss to compile you have to install sass compiler using `pnpm add -D sass`.

```ts
// default theme styles
import '@anu-vue/preset-theme-default/dist/styles.scss'
```

Certainly, we can provide a CSS file for preset-theme-default in upcoming versions by updating `preset-theme-default` build process but for now, I suggest you just add scss compiler.

**Comment by ManUtopiK** [comment]
> we can provide a CSS file for preset-theme-default in upcoming versions

Sure, it will be better to not install another dependency in our project.

**Comment by jd-solanki** [comment]
https://github.com/jd-solanki/anu/commit/61168eaabd74ba879ed4c83b9fed055038365b17
